### ISSUE TITLE
3D model doesn't show in kicad (no kicad compatible 3D file)

### ISSUE THREAD

**Issue by ghost** [O-Shovah/Kicad#1]
Hi,

First of all, thank you for the hard work, it saved me a lot of trouble!

Only thing i'd like to add is the 3D model for kicad 3d render of the board... Do you know how to convert the step file in wml whatever?

thank you,

Nick

**Comment by O-Shovah** [comment]
Hello Nick,

I'm glad to hear someone can make use of these files :)

Basically Kicad should be able to display .stp files directly so i skipped creating a .wrl file.

But that might be a problem if you are running an oder Version of Kicad ( I'm on the nightly).
Which version are you running ?

Another more simple thing could be that you have to adjust the file path.
The path included in the Github footprint is : "${KIATOMIC}/Pixhawk_2-Cube/Pixhawk_2-Cube.stp"
so you either have to create the path variable "KIATOMIC"  or change the path accordingly
to the path which contains the .stp file of the cube.

I hope thats a start

Jens
 
![breakout-platine-cube](https://user-images.githubusercontent.com/1301676/30899704-4fd3667e-a361-11e7-80a0-42fc0ee2b176.jpg)

**Comment by O-Shovah** [comment]
I Just created an uploaded a .wrl version of the 3D shape.
The path is alike the .stp version.
I recommend to use the .stp file though for later exporting the PCB to cad programs.
Keep in mind that if you adjust the path variable that Kicad will load 
both 3D shapes on top of each other which might look odd.

**Comment by ghost** [comment]
Hi Jens,

Thank you very much for the very fast update and solution, I really appreciate that!

I'm running kicad 4.0.4 and it doesn't recognise the step file.. don't really know why. Seems to work with the mrl you posted though, even if the position ofsets are wrong, I'll be able to correct that :)

If you want, I also had a monobloc schematic i designed before i found your work, so maybe it could be useful to someone?

nick

**Comment by O-Shovah** [comment]
Hi Nick,

glad to hear it somehow worked for you now.
Can you tell me in which direction and by how much the offsets were wrong for you ?

It certainly would be a nice addition if you can publish your monobloc schematic for people 
to choose between both variants.

Jens

**Comment by ghost** [comment]
Hi Jens,

Sorry I forgot to update you here... After I rebooted Kicad, everything was fine... Don't know why it was ofseted in the first place....
Here is a picture with it on the board :)
![pixhawk_carrier](https://user-images.githubusercontent.com/8006642/31214045-bbeab86e-a9a9-11e7-9bac-c85c6d8be9f8.JPG)

I'll upload my schematic now then! :)

nick
